# this is h1
## this is h2
### this is h3
#### this is h4
##### this is h5
###### this is h6

# esc+m ---->  convert  codecell to markdown cell
#  ctrl+enter----> for executing current shell
#  esc+a ---->  insert the shell above the current shell
#  esc+b---> insert the shell below the current shell

# NUMPY
. Numerical python
    Multidimensional
    Less time to execute
    Numerical operation

# for importing num py

In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [3]:
d1=np.array([78,94,67,87,98,89])
d1

array([78, 94, 67, 87, 98, 89])

In [4]:
d1.shape

(6,)

In [5]:
d1.size

6

# number of dimensions

In [6]:
d1.ndim

1

In [7]:
d1

array([78, 94, 67, 87, 98, 89])

In [8]:
# here we are getting 4th element from the array
d1[4]

98

In [9]:
d1[0:3]

array([78, 94, 67])

In [10]:
data=np.array(["ranga",123,"CSE","C",89.98],dtype='<U5')

In [11]:
import time
start_time= time.time()
list1=[x for x in range(1,100000)]
list2=[y for y in range(1,100000)]
op = list(map(lambda x,y : x*y, list1,list2))
end_time=time.time()
print("time take by list concept",end_time-start_time)

time take by list concept 0.03124856948852539


In [12]:
import time
start_time1=time.time()
ar1= np.array(list1)
ar2=np.array(list2)
ar1*ar2
end_time1=time.time()
print("time taken by numpy is",end_time1-start-time1)

NameError: name 'start' is not defined

In [13]:
import time
start_time1=time.time()
ar1= np.array(list1)
ar2=np.array(list2)
ar1*ar2
end_time1=time.time()
print("time taken by numpy is",end_time1-start_time1)

time taken by numpy is 0.0


# Multidimensional array

In [14]:
# 2-D array declaration
d2=np.array([[45,74,36],[96,87,69],[14,25,63]])
d2

array([[45, 74, 36],
       [96, 87, 69],
       [14, 25, 63]])

In [15]:
d2.shape

(3, 3)

In [16]:
d2.ndim

2

In [17]:
d2.size

9

In [18]:
d2[0]

array([45, 74, 36])

In [19]:
d2[0[1]]

<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<ipython-input-19-15a41fbf0dba>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  d2[0[1]]


TypeError: 'int' object is not subscriptable

In [20]:
d2[2]

array([14, 25, 63])

In [21]:
d2[0][1]

74

In [22]:
d2[0]

array([45, 74, 36])

In [23]:
d2[0][2]

36

In [24]:
d2[0,2]

36

In [25]:
d2[1].max()

96

In [26]:
d2[1].min()

69

In [27]:
np.max(d2[1])

96

In [28]:
np.min(d2[1])

69

In [29]:
# for printing columns of 2-d array
d2[:,2]

array([36, 69, 63])

In [30]:
np.min(d2[0])

36

# for printing minimum value in particular column

In [31]:
d2[:,0].min()

14

In [32]:
d2[0].sum()

155

In [33]:
d2.sum()

509

In [34]:
d2.sum(axis=0)

array([155, 186, 168])

In [35]:
d2

array([[45, 74, 36],
       [96, 87, 69],
       [14, 25, 63]])

In [36]:
d2.sum(axis=1)

array([155, 252, 102])

In [37]:
d3=np.array([[[1,2,3],[4,3,6]],[[7,8,9][10,11,12]]])
d3


<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-37-41b6683edf5e>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  d3=np.array([[[1,2,3],[4,3,6]],[[7,8,9][10,11,12]]])


TypeError: list indices must be integers or slices, not tuple

In [38]:
d3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
d3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
d3[0,0]

array([1, 2, 3])

In [41]:
d3[0,0,1]

2

# Arange()

In [42]:
for i in range(1:11):
    i

SyntaxError: invalid syntax (<ipython-input-42-23d440448301>, line 1)

In [43]:
for i in range(1,11):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 

In [44]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [45]:
for i in arrange(1,11):
    print(i)

NameError: name 'arrange' is not defined

In [46]:
np.arrange(1,10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [47]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
for i in arange(1,11):
    print(i)

NameError: name 'arange' is not defined

In [49]:
for i in range(1,6,1.5):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [50]:
for i in range(1.0,5.0,1.5):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [51]:
for i in range(1,6,2):
    print(i)

1
3
5


In [52]:
np.arange(1,10,1.5)

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

In [53]:
np.linspace(1,10,0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [54]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [55]:
# zeros matrix
print(np.zeros([10,20]))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [56]:
print(np.zeros([3,5]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [57]:
print(np.ones([5,6]))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [58]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
np.tail(10,5,5)

AttributeError: module 'numpy' has no attribute 'tail'

In [60]:
np.tile(10,[5,5])

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [61]:
d21=np.array([[14,25,36,41,52],
             [24,51,35,15,16]])
d21

array([[14, 25, 36, 41, 52],
       [24, 51, 35, 15, 16]])

In [62]:
add_marks=np.tile(5,[2,5])
add_marks

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [63]:
final_marks=d21+add_marks
final_marks

array([[19, 30, 41, 46, 57],
       [29, 56, 40, 20, 21]])

In [64]:
mat=np.array([[1,10,20],[2,20,30],[3,45,55]])
mat

array([[ 1, 10, 20],
       [ 2, 20, 30],
       [ 3, 45, 55]])

In [65]:
np.linalg.inv(mat)

array([[-1.66666667,  2.33333333, -0.66666667],
       [-0.13333333, -0.03333333,  0.06666667],
       [ 0.2       , -0.1       ,  0.        ]])

# for findout the eigen values

In [66]:
np.linalg.eig(mat)

(array([79.2418833 , -0.76390403, -2.47797927]),
 array([[-0.27476378, -0.98372828, -0.86503683],
        [-0.44175308, -0.11022856, -0.37213216],
        [-0.85402523,  0.14187439,  0.33649509]]))

# random
## in random values, valuesare in between 0 and 1


In [67]:
np.random.random(10)

array([0.90146471, 0.00856296, 0.62635627, 0.09383206, 0.81538104,
       0.08781759, 0.18549502, 0.30364473, 0.20753054, 0.83532333])

In [68]:
np.random(400)

TypeError: 'module' object is not callable

In [70]:
np.random.randint(10)

2

In [71]:
np.random.randint(40)

20

In [72]:
np.random.randint(5,7)

5

In [73]:
np.random.randint(5,5)

ValueError: low >= high

In [74]:
np.random.randint(5,6)

5

In [75]:
np.random.randint(5,7,1)

array([5])

In [76]:
np.random.randint(1,10,2)

array([4, 8])

In [77]:
np.random.randint(1,10,7)

array([9, 6, 7, 6, 7, 9, 9])

In [78]:
np.random.randint(1,5,7)

array([3, 2, 4, 2, 2, 2, 3])

In [79]:
np.random.randint(10,25,25)

array([12, 17, 22, 21, 11, 15, 18, 10, 22, 20, 21, 14, 22, 10, 14, 16, 10,
       18, 14, 21, 16, 10, 22, 10, 23])

In [80]:
np.random.randint(10,25,[4,6])

array([[22, 10, 24, 21, 24, 21],
       [23, 16, 14, 14, 23, 19],
       [16, 20, 23, 13, 15, 10],
       [18, 23, 13, 16, 22, 10]])

In [81]:
np.random.rand(10)

array([0.39504075, 0.78916226, 0.07243813, 0.31892471, 0.12001354,
       0.60446293, 0.91004488, 0.46649145, 0.44771927, 0.1408543 ])

In [82]:
np.arrange(1,13)

AttributeError: module 'numpy' has no attribute 'arrange'

In [83]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [84]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [85]:
np.arange(1,49).reshape(4,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [1]:
np.sin(90)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
np.sin(90)

0.8939966636005579

In [4]:
np.arcsin(1)

1.5707963267948966

In [5]:
array=np.array([1,2,3])

In [6]:
array

array([1, 2, 3])

In [7]:
# for finding the max value index
array.argmax()

2

In [8]:
array.argmin()

0

In [9]:
section1=np.array(np.random.randint(10,20,[4,4]))
section1

array([[18, 14, 11, 17],
       [11, 17, 18, 10],
       [13, 16, 14, 17],
       [16, 19, 14, 19]])

In [10]:
section2=np.array(np.random.randint(1,10,[4,4]))

In [11]:
section2

array([[6, 7, 7, 7],
       [4, 5, 9, 6],
       [1, 2, 2, 2],
       [8, 1, 5, 8]])

In [14]:
np.vstack((section1,section2))

array([[18, 14, 11, 17],
       [11, 17, 18, 10],
       [13, 16, 14, 17],
       [16, 19, 14, 19],
       [ 6,  7,  7,  7],
       [ 4,  5,  9,  6],
       [ 1,  2,  2,  2],
       [ 8,  1,  5,  8]])

In [13]:
np.vstack((section1,section2))

array([[18, 14, 11, 17],
       [11, 17, 18, 10],
       [13, 16, 14, 17],
       [16, 19, 14, 19],
       [ 6,  7,  7,  7],
       [ 4,  5,  9,  6],
       [ 1,  2,  2,  2],
       [ 8,  1,  5,  8]])

In [15]:
np.hstack((section1,section2))

array([[18, 14, 11, 17,  6,  7,  7,  7],
       [11, 17, 18, 10,  4,  5,  9,  6],
       [13, 16, 14, 17,  1,  2,  2,  2],
       [16, 19, 14, 19,  8,  1,  5,  8]])

In [16]:
np.column_stack((section1,section2))

array([[18, 14, 11, 17,  6,  7,  7,  7],
       [11, 17, 18, 10,  4,  5,  9,  6],
       [13, 16, 14, 17,  1,  2,  2,  2],
       [16, 19, 14, 19,  8,  1,  5,  8]])

In [17]:
section1+section2

array([[24, 21, 18, 24],
       [15, 22, 27, 16],
       [14, 18, 16, 19],
       [24, 20, 19, 27]])

In [18]:
section1*section2

array([[108,  98,  77, 119],
       [ 44,  85, 162,  60],
       [ 13,  32,  28,  34],
       [128,  19,  70, 152]])

In [19]:
section1@section2

array([[311, 235, 359, 368],
       [232, 208, 316, 295],
       [292, 216, 348, 351],
       [338, 254, 406, 406]])

In [20]:
section1/section2

array([[ 3.        ,  2.        ,  1.57142857,  2.42857143],
       [ 2.75      ,  3.4       ,  2.        ,  1.66666667],
       [13.        ,  8.        ,  7.        ,  8.5       ],
       [ 2.        , 19.        ,  2.8       ,  2.375     ]])

In [21]:
section1//section2

array([[ 3,  2,  1,  2],
       [ 2,  3,  2,  1],
       [13,  8,  7,  8],
       [ 2, 19,  2,  2]], dtype=int32)

In [22]:
section1%section2

array([[0, 0, 4, 3],
       [3, 2, 0, 4],
       [0, 0, 0, 1],
       [0, 0, 4, 3]], dtype=int32)

In [23]:
section1**section2

array([[  34012224,  105413504,   19487171,  410338673],
       [     14641,    1419857,  790794752,    1000000],
       [        13,        256,        196,        289],
       [         0,         19,     537824, -196306143]], dtype=int32)

In [24]:
secton1.transpose()

NameError: name 'secton1' is not defined

In [25]:
section1.transpose()

array([[18, 11, 13, 16],
       [14, 17, 16, 19],
       [11, 18, 14, 14],
       [17, 10, 17, 19]])

In [26]:
section1.trace()

68

In [27]:
section1.dot(section2)

array([[311, 235, 359, 368],
       [232, 208, 316, 295],
       [292, 216, 348, 351],
       [338, 254, 406, 406]])

In [30]:
np.hsplit(section1,2)

[array([[18, 14],
        [11, 17],
        [13, 16],
        [16, 19]]),
 array([[11, 17],
        [18, 10],
        [14, 17],
        [14, 19]])]

In [31]:
np.vsplit(section1,2)

[array([[18, 14, 11, 17],
        [11, 17, 18, 10]]),
 array([[13, 16, 14, 17],
        [16, 19, 14, 19]])]

In [33]:
np.hsplit(section1,[2,2])

[array([[18, 14],
        [11, 17],
        [13, 16],
        [16, 19]]),
 array([], shape=(4, 0), dtype=int32),
 array([[11, 17],
        [18, 10],
        [14, 17],
        [14, 19]])]

In [34]:
np.abs(100.25)

100.25

# abs is used for converting negative value to postive value

In [35]:
np.abs(-100)

100

In [36]:
np.all(section1>0)

True

In [37]:
np.any(section1<0)

False

In [38]:
np.round(12.63)

13.0

In [39]:
np.floor(12.63)

12.0

In [40]:
np.ceil(10.23)

11.0